- hosts: localhost
  tasks:
    - ec2:
        aws_access_key: AKIAUAQNJGIFZRUJF5G6
        aws_secret_key: 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
        key_name: docker
        group: launch-wizard-1
        instance_type: t2.micro
        image: ami-041d6256ed0f2061c
        wait: yes
        wait_timeout: 500
        count: 1
        instance_tags: 
          db: postgres
        region: ap-south-1
        vpc_subnet_id: subnet-ac18ebc7
        assign_public_ip: yes


